spring:
  application:
    name: notification
server:
  port: 8886

fcm:
  service-account-file: google.json
  project-id: conting-d3d77

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}