server:
  port: 8882


spring:
  application:
    name: ticket-service
  r2dbc:
    url: r2dbc:mariadb://localhost:9992/ticket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    com.c209.ticket: DEBUG