server:
  port: 8883

spring:
  application:
    name: ticket-service
  r2dbc:
    url: r2dbc:mariadb://${TICKET_HOST}:${TICKET_DB_PORT}/ticket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${TICKET_DB_USERNAME}
    password: ${TICKET_DB_PASSWORD}
  data:
    redis:
      host: ${TICKET_HOST}
      port: 6379

logging:
  level:
    com.c209.ticket: debug
    io.lettuce.core: debug
kafka:
  url: ${KAFKA_URL}