server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: catalog-service
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${CATALOG_DB_URL}
    username: ${CATALOG_DB_USER_NAME}
    password: ${CATALOG_DB_PASSWORD}
    hikari:
      max-lifetime: 160000

logging:
  level:
    com.c209.catalog: INFO
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:7777/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    hikari:
      max-lifetime: 160000

logging:
  level:
    com.c209.catalog: DEBUG