# gateway
server:
  port: 8888

spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalLoggingFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE}
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: ${USER_SERVICE}
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter
        - id: seat-service
          uri: ${SEAT_SERVICE}
          predicates:
            - Path=/seat/**
          filters:
            - AuthorizationHeaderFilter
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
jwt:
  access-key: ${JWT_ACCESS}

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "http://localhost"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}

---

