


spring:
#  output:
#    ansi:
#      enabled: always
  application:
    name: seat
  r2dbc:
    url: r2dbc:mariadb://localhost:9999/seat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  kafka:
#    bootstrap-servers: localhost:9092
#  sql:
#    init:
#      mode: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:9999/seat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    hikari:
      max-lifetime: 160000
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
server:
#  shutdown: graceful
  port: 8889
#  error:
#    include-message: always
#    include-exception: true
#    include-stacktrace: always
logging:
  level:
    com.c209: debug


---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/payment
  sql:
    init:
      mode: always
      data-locations: ""