

server:
  port: 8881

spring:
  profiles:
    active: prod
    group:
      local:
        - common
      prod:
        - common
      test:
        - common
---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: queue-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${USER_DB_URL}
    username: root
    password: 1234
    hikari:
      max-lifetime: 160000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  data:
    redis:
      host: 127.0.0.1
      port: 6380


logging:
  level:
    com.c209.queue: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${QUEUE_DB_URL}
    username: ${QUEUE_USER_NAME}
    password: ${QUEUE_DB_PASSWORD}
    hikari:
      max-lifetime: 160000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  data:
    redis:
      host: ${QUEUE_HOST}
      port: 6380


logging:
  level:
    com.c209.queue: INFO

---
spring:
  config:
    activate:
      on-profile: prod-cluster
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${QUEUE_DB_URL}
    username: ${QUEUE_USER_NAME}
    password: ${QUEUE_DB_PASSWORD}
    hikari:
      max-lifetime: 160000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  data:
    redis:
      cluster:
        nodes: ${QUEUE_HOST}:6371,${QUEUE_HOST}:6372,${QUEUE_HOST}:6373,${QUEUE_HOST}:6374,${QUEUE_HOST}:6375,${QUEUE_HOST}:6376
        max-redirects: 3
      password: bitnami
      connect-timeout: 500ms
  session:
    redis:
      flush-mode: on_save


logging:
  level:
    com.c209.queue: INFO


---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      host: 127.0.0.1
      port: 6380


logging:
  level:
    com.c209.queue: DEBUG

