

server:
  port: 8882


spring:
  application:
    name: pay-service


  r2dbc:
    url: r2dbc:mariadb://localhost:7779/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  datasource:

    url: jdbc:mariadb://localhost:7779/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    hikari:
      max-lifetime: 160000
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}




logging:
  level:
    com.c209.payment: DEBUG


iamport:
  userId: ${IAMPORT_USER_ID}
  apiKey: ${IAMPORT_API_KEY}
  secret: ${IAMPORT_SECRET}


