

server:
  port: 8882


spring:
  application:
    name: pay-service


  r2dbc:
    url: r2dbc:mariadb://${PAY_DB_URL}/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${PAY_DB_USER_NAME}
    password: ${PAY_DB_PASSWORD}
  datasource:

    url: jdbc:mariadb://${PAY_DB_URL}/payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${PAY_DB_USER_NAME}
    password: ${PAY_DB_PASSWORD}
    hikari:
      max-lifetime: 160000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER}



kafka:
  url: ${KAFKA_URL}

logging:
  level:
    com.c209.payment: DEBUG

service:
  seat:
    url: ${SEAT_SERVICE}

iamport:
  userId: ${IAMPORT_USER_ID}
  apiKey: ${IAMPORT_API_KEY}
  secret: ${IAMPORT_SECRET}


